# Generated by Django 5.2.9 on 2025-12-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField()),
                ('user_legacy_id', models.IntegerField()),
                ('product_legacy_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
